### ISSUE TITLE
Handling unspecied entries in primary directory filter  

### ISSUE THREAD

**Issue by ColmMassey** [DigitalCommons/mykomap#160]
If there are empty cells in an organisation's data in a field that is being used as the primary filter in the directory panel, there is no title displayed, but a even though it is possible to select it and view all the co-ops that don't specify anything in that field. 

Insert a title Unspecified. 
![Untitled](https://user-images.githubusercontent.com/1162642/199614551-cdbbe201-4521-4dd5-85ed-4fe263079432.png)

**Comment by wu-lee** [comment]
Why this blank occurs
- The Co-ops UK sector field (`cukSector`) comes from the standard.csv column of that name
- This is interpreted as plain text (so not a vocab in any sense, currently)
- The directory pane can handle it nevertheless (because there are a relatively small number of values)
- It used to be that blank values in the CSV resulted in null values in the SPARQL results
- Up until now, blanks were retained as blanks in the CSV data
- This means the code which groups nulls into "All Entries" left these values in as their own category (and why this blank wasn't visible on earlier CUK maps)
- Now, the blanks appears as an extra (blank) category.

I've updated the CSV transformation rules so that blanks in text fields are interpreted as nulls.  (See commit f6fd28069.)

This means that if they're left as nulls by the transform rules, no blank category is added (as before. But they can also now be translated into a default value by the transform (by configuration), such as "Unspecified".  This means the coops-uk map can be configured to do this, which results in the "Unspecified" category appearing. I think this does the job (see 0595d813).

**Comment by ColmDC** [comment]
Seems like an elegant solution.
