### ISSUE TITLE
Multi-language support not available

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap#182]
**Describe the bug**
If you request a non english view of the map on the latest development version of mykomap@3.0.4_677b5e7-modified-dev

on https://dev.maps.solidarityeconomy.coop/temp/?language=KO

all the terms are still in English

**To Reproduce**
1. load map using url above
2. Nothing is in Korean!

**Expected behavior**
You should be able to see all the core text used in the app in Korean

**Comment by ColmDC** [comment]
@wu-lee thinks it may be an error in the configuration rather than a new MykoMap bug itself.

**Comment by wu-lee** [comment]
Co-ops UK test now deployed, plus data including a French translation in the vocabs.

See:
- https://dev.maps.solidarityeconomy.coop/temp/coopsuk/
- https://dev.maps.solidarityeconomy.coop/temp/coopsuk/?language=FR

Filter drop-downs seem to have French translations, the directory panel does not.

Furthermore, the directory cannot do that in this case. Because the "Sector (Coops UK)" field used on the directory is not a vocabulary field, the Co-ops UK's data supplies the category values and title used. All Mykomap can do therefore is infer the title from the field name, and the display values from the data seen.

The map pin pop-ups seem to have translations on fields which are vocab fields. But not on "Sector (Coops UK)", nor "SIC Section", because ditto.

Some pop-ups have undefined values - e.g. "Type de structure: undefined" on Keoldale Sheep Stock Club (an outlier pin on the top of Scotland).

The reason for this is that the French vocab is missing a translation for OS130 AKA Community Benefit Society.  This would need to be fixed upstream in the vocab definitions we have.

Overall, however, apart from these "undefined" values, it seems to be working?

(I think there should  be more checking performed in mykomap and upstream for undefined vocab fields, but also the failure mode should not just be to show "undefined", but either the English term - there is a precedent for this - and/or a language specific "untranslated" value)

**Comment by ColmDC** [comment]
I am now seeing the same results you describe above. It required me to clear my caches first though.

**Comment by ColmDC** [comment]
> (I think there should be more checking performed in mykomap and upstream for undefined vocab fields, but also the failure mode should not just be to show "undefined", but either the English term - there is a precedent for this - and/or a language specific "untranslated" value)

I wonder it we could easily rig debug/release versions, where in debug it displayed 'Untranslated term' and in release it put the deafult language.

**Comment by ColmDC** [comment]
> I wonder it we could easily rig debug/release versions, where in debug it displayed 'Untranslated term' and in release it put the deafult language.

I think these improvements should go in a new ticket, and we can close this one?

**Comment by wu-lee** [comment]
New issue: https://github.com/DigitalCommons/mykomap/issues/188
