### ISSUE TITLE
Markers and dialogs disappearing 

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap#220]
**Describe the bug**
Filtering for the county East Timor shows no markers and dialogs and markers remain invisible until all entries is selected.

**To Reproduce**
Go here and follow video Follow video 

https://dev.maps.solidarityeconomy.coop/ncba/

[Video](https://www.awesomescreenshot.com/video/21054371?key=b6879d5696eb879ea75fe8f0dbb510c8)

**Expected behavior**
The markers and dialog should appear

**Desktop (please complete the following information):**
 - Firefox on Windows 10 - 
 - mykomap@3.1.0

**Comment by wu-lee** [comment]
I think I've fixed this by fixing an (apparently related) problem, in which if the `filterableFields` config was fields A, B and C then it should have been showing A in the directory - but wasn't, another was used, apparently indeterminately. 

This fix involved stopping indexing field field indexes with the field *titles* (a human readable string, not guaranteed unique) with their ID (a unique alphanumeric value).

Fixing this allowed the first item of `filterableFields` to be used to get the right index directly. Not possible when the indexes were indexed by field title, as the relationship from field to its title is a circuitous one.

Having fixed this, I can't reproduce the issue described above.

The fix is currently deployed on the dev NCBA map, which uses a fixed version of Mykomap (3.1.1)

**Comment by ColmDC** [comment]
Looks fixed.
