### ISSUE TITLE
Update pop up dialog contents for workers.coop

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap#233]
## Description
[workers.coop]
Code the workers.coop pop up dialogs to display the data available for each co-op as follows

**Left Side**
[Name]
“Website” [https://](https://www.appin.scot/community-coop/intro) 

“Industry” [Organisation extras: Industry Sector]
“Sic Code” [Sic Code]
“Ownership type” [Organisation extras: Ownership type]
“Legal form” [Organisation extras: Legal Form]
“Registered Number” [Registered Number]
“Status” [Organisation extras: Registered Status]

[Organisation extras: Description]

**Right Side**
Contact
Street Address
Supplemental Address 1	
Supplemental Address 2	
City	
Postal Code
Email

**Comment by lin-d-hop** [comment]
This sounds like it might be a good one to pair on for Marcel or Rohit to dive into MykoMaps.

Out of interest @wu-lee, does this happen in a config? How does this impact the intention of bringing together different MykoMaps under the same codebase?

**Comment by wu-lee** [comment]
> Out of interest @wu-lee, does this happen in a config? How does this impact the intention of bringing together different MykoMaps under the same codebase?

Mykomap has a default pop-up dialogue, which because the base configuration is only a few fields like name, location and (possibly) description, can only really show those cases.

They way the pop-up is customised currently is to implement a call-back function. This accepts a reference to an object delivering access to most of Mykomap's internal APIs, and another representing the "initiative" for the pin in question (AKA the entity, typically an organisation). This call-back returns an HTML string which is then stuffed into the dialogue verbatim, and should use the appropriate CSS classes and styles accordingly.

In other words, it's a bit like programming your VCR via a panel which opens and exposes the wiring and PCBs - Good luck making sense of that! And remember to use rubber gloves.

Consequentially it's a typical pain-point for any new map.  And upgrading any map, when that API changes.  Plus some things are not trivial to implement. So there's a log of cut-and-pasting between maps, various bits of code get cannibalised from one project to another. Also, there's no documentation.

I've no love for it, but implementing something which can replace that - i.e what I think you mean by "bring together different Mykomaps" - needs to be able to cover all of (or a lot of the main) current and upcoming use-cases for field combinations: single and multi value; literal values and taxonomies; addresses comprised of multiple fields from a historical "normal" case which may in future cases be dependent on the source data; telephone numbers, emails and social media links, website URLs, descriptions in plain text, rich text, HTML.  And so on. 

Therefore it needs a bit of chin-stroking cogitation to tame this spiky free-for-all into something which is less of a nightmare and also delivers a pop-up which could replace most of the custom ones. I have some ideas, but I don't expect it to be a small amount of work.

**Comment by ColmDC** [comment]
So I think for the workers.coop dialog, would it not still be useful for one of them to follow you implementing it, so they have eyes on the current method. So not quite pair programming, but some knowledge sharing?

**Comment by wu-lee** [comment]
With the disclaimer that this might be hard to do quickly and clearly, I'm okay doing this if everyone else is.

**Comment by ColmDC** [comment]
> With the disclaimer that this might be hard to do quickly and clearly, I'm okay doing this if everyone else is.

Given that the workers.coop project is way late and the ball is now in our court, I'd rather not do anything that slows it down much more. So @wu-lee please implement the workers.coop dialog but with someone looking over your shoulder if you can coordinate in next couple of days, but not necessarily them expecting to follow all your steps.

**Comment by ColmDC** [comment]
@wu-lee should this be in InProgress, or at least Dev Ready?

**Comment by wu-lee** [comment]
Yes - sorry. Discussion implied it was dev-ready I thought? Is it not?

**Comment by wu-lee** [comment]
Anyway, there is a map with populated pop-ups here now. Note, it has a link to a form for reporting errors, but the form is not there. 


https://dev.maps.coop/workers-coop/

**Comment by ColmDC** [comment]
> Yes - sorry. Discussion implied it was dev-ready I thought? Is it not?

From discussion, yes, but we are trying to keep the Kanban reflecting where each piece of work is at. Did anyone shadow you doing this?

**Comment by ColmDC** [comment]
Did anyone shadow you working on the popup?

**Comment by wu-lee** [comment]
No,  I just got on with it. Took some fiddling around, an attempt to tidy the code, and I needed to create the vocabs file(s), doesn't seem to be a SIC vocab, lots of lose ends.

SIC Code is listed as a required field on the panel: but this has literally tens of thousands of terms. gov.uk use a slimmed down version, even then - thousands. So I'm inferring that probably it's the SIC *Section* field they actually want, which only has 20ish terms.  But I still needed to make a vocab  table for that, because I don't think that's a category Graham sent labels for.

**Comment by wu-lee** [comment]
SIC Code: this is listed as a required field on the panel. But: it has literally tens of thousands of terms. gov.uk use a slimmed down version, even then - thousands. So I'm inferring that probably it's the SIC *Section* field they actually want, which only has 20ish terms.  But I still needed to make a vocab  table for that, because I don't think that's a category Graham sent labels for.

**Comment by ColmDC** [comment]
>So I'm inferring that probably it's the SIC Section field they actually want,

Assume that.

**Comment by ColmDC** [comment]
If an email is not present, the text [undefined](mailto:undefined) is displayed. Change to not displaying anything if no email is present.

**Comment by wu-lee** [comment]
> If an email is not present, the text `undefined` is displayed. Change to not displaying anything if no email is present.

Ok, fix applied, try again.

I've also added the "about" text spec'ed in the document [here][1]. Is there a separate issue for that?

[1]: https://docs.google.com/document/d/1WkHl4oGmb3dtkcsdUqlGBx_mq9nWP1AoJNLd0-9HPc8/edit?pli=1

**Comment by ColmDC** [comment]
> I've also added the "about" text spec'ed in the document [here](https://docs.google.com/document/d/1WkHl4oGmb3dtkcsdUqlGBx_mq9nWP1AoJNLd0-9HPc8/edit?pli=1). Is there a separate issue for that?

I think only as tick boxed item half way down https://github.com/DigitalCommons/mykomap/issues/207#issuecomment-1836440395.

**Comment by ColmDC** [comment]
Happy for this to move to review.

**Comment by ColmDC** [comment]
>    4) Dialog size. On smaller (but not mobile) screens or when email addresses are long the email wraps. Should we reposition it to the wider panel, or widen the right panel, or increase the overal size of the dialog?

Yes- position just under the web address? then it may make more sense to change "contact"  to "Address"

**Comment by wu-lee** [comment]
Email moved, title changed. 

Default location updated as per John's email:
>     1) When the geolocation fails to return a lat long, the dialog for the co-op appears in a default location. It is currently deep in the Atlantic Ocean. Where would you like it to be? Holyoake house? Please provide a lat long.
> > Go for:
> > Long: 53.619840 Lat: -2.160080 (Rochdale Pioneers Museum)

(The data needs updating manually so that Plymouth-based co-op moves back to the UK; or better, added to the list of regularly updated datasets. Will do that later this weekend.)

**Comment by ColmDC** [comment]
Great closing this.
