### ISSUE TITLE
[Workers.coop] Add final configuration options for workers.coop MM

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/mykomap#239]
**Please track against the clockify project [Workers.coop]**

## Description
Finished setting the configuration options for the Workers.coop map as follows
- [x] Populate About box with following content (https://docs.google.com/document/d/1WkHl4oGmb3dtkcsdUqlGBx_mq9nWP1AoJNLd0-9HPc8/edit#bookmark=id.1eimob82ifmp)
- [x] Change default MM colours to #ef9600 
- [x] Add workers.coop Logo to to right of screen
- [x] Set up Directory and Filter Options to use [specified settings](https://docs.google.com/document/d/1WkHl4oGmb3dtkcsdUqlGBx_mq9nWP1AoJNLd0-9HPc8/edit?pli=1#bookmark=id.2yh4uu944dq4) other than Status

**Comment by wu-lee** [comment]
Ok, so:
- pop-up fields configured as per #223 
- about box as spec'ed above
- filtered fields configured as spec'ed above
- (text) searchable fields configured to include name and description (not spec'ed but this seems a sensible choice)
- logo added (taken from website)
- font, colours and other styles tweaked to emulate workers.coop site

Deployed here: https://dev.maps.coop/workers-coop/

**Comment by ColmDC** [comment]
Looking sweet.

**Comment by ColmDC** [comment]
>(text) searchable fields configured to include name and description (not spec'ed but this seems a sensible choice)

Sensible. 

>pop-up fields configured as per https://github.com/DigitalCommons/mykomap/issues/223
Are you proposing we add these companies house links?

>font, colours and other styles tweaked to emulate workers.coop site
Can you make the marker colour orange too?

**Comment by wu-lee** [comment]
> > pop-up fields configured as per #223
> 
> Are you proposing we add these companies house links?

I think I might have linked to the wrong issue... I meant #233  The CH links are not in the spec but we totally could do that if John think's a good addition.

> > font, colours and other styles tweaked to emulate workers.coop site
>
> Can you make the marker colour orange too?

Maybe ... looking into that.  The problem is that the current mechanism uses PNG images with a pre-selected range of about 18 colours. There might be a way to mutate a PNG into having a different colour using only CSS, although probably with caveats. Alternatively I could mint a new PNG and try and override the existing one.

**Comment by wu-lee** [comment]
Ok, managed it, check the link above again.. Used a custom pin image. Getting the exact colour was surprisingly tricky.

**Comment by ColmDC** [comment]
Looking great. I will ping workers.coop to take a look and see if they are happy enough with this to move to release.

**Comment by ColmDC** [comment]
>> 1) When the geolocation fails to return a lat long, the dialog for the co-op appears in a default location. It is currently deep in the Atlantic Ocean. Where would you like it to be? Holyoake house? Please provide a lat long.

>Go for:
>Long: 53.619840 Lat: -2.160080 (Rochdale Pioneers Museum)


>>    2) There is a co-op which is getting positioned in Plymouth US rather than UK. I think it should be at 50.36862, -4.1731. Can you please set that lat long in the CRM?


>Done
How often is the data pull being triggered?

**Comment by wu-lee** [comment]
Default location updated as per John's email.

I've manually updated the data so that Plymouth-based co-op moves back to the UK.  (It also needed the map config being fixed, as it was using the dev.data.digitalcommons.coop server - two servers being a source of confusion.)

The data isn't being pulled automatically yet.

This is just as well, as there's also a duplicate organisation in the data - looks similar to the problem ICA were having, a two-valued field creating two near-identical rows in the data. In this case it was Footprint Workers Co-op, and there were two website URLs, one an invalid URL. If there's a duplicate the map doesn't render: duplicate IDs are a fatal error. I manually dropped the incorrect row for now and redeployed the data. This is a potential fragility if it could happen again, so I've emailed Graham to let him know about this and asked him to remove the duplicate URL.

So I won't add workers.coop to the list of regularly updated datasets until this has been fixed upstream. (Or until I write a workaround in the converter to skip one of the duplicates, this might be preferable, but it may pick the "wrong" row, and it will be hard to notice if it happens again.)

**Comment by wu-lee** [comment]
> (Or until I write a workaround in the converter to skip one of the duplicates, this might be preferable, but it may pick the "wrong" row, and it will be hard to notice if it happens again.)

Have done that, so the WC data conversion will be converted automatically (every 10 minutes, as there's no indicator of changes), but duplicate orgs will be dropped. In this case, this seems to result in the right one being chosen, but if the order changes, and the wrong one is chosen, the worst case is that Footprint will have a bad URL.

It's likely we need a more visible way to spot warnings about this, however. These are reported but only in the logs for the data factory service `se_open_data`, which live on the server.

**Comment by ColmDC** [comment]
I have upgraded this to an [issue](https://github.com/DigitalCommons/workers-coop-map/issues/2). Note the need to make more visible to Workers.coop issues like duplicate organisation in the data in that issue.

**Comment by wu-lee** [comment]
No reply from Graham so far about the form, so we might want to finish this off by putting a mailto link on the map for now, instead of the form.  I don't think there was an email address nominated for this, however?

**Comment by ColmDC** [comment]
Remaining work in #234 and #221

**Comment by ColmDC** [comment]
All this functionality is working bar what is covered in https://github.com/DigitalCommons/mykomap/issues/247, so closing.
