### ISSUE TITLE
[CWM] Whiteboarding session for creating the MM backend

### ISSUE THREAD

**Issue by lin-d-hop** [DigitalCommons/mykomap#266]
*Track under CWM in Clockify*

## Description
Let's create the tickets for the first steps in creating the MM backend.

This whiteboarding session is to create tickets that will get us to the point that we have:
- Created server in node with existing MM code
- Strip out all of the FE code
- Created an initial mock fake data API response from BE. This is more about testing infrastructure than finalising the response format, to enable this not to be blocked by API design.

## Acceptance Criteria
- Whiteboard meeting
- Issues created

**Comment by rogup** [comment]
In a comment from #265:

> @wu-lee: I think the main question left now is what goes on the back-end. (To think about this briefly, I would suggest something which works smoothly with Swagger/OpenAPI and is small and simple and aimed at rapid prototyping. I see that [NocoDB says it supports Swagger](https://docs.nocodb.com/0.109.7/developer-resources/accessing-apis/), and we can run this on our Cloudron server, which simplifies deployment massively)

Are you suggesting that we don't have a backend server at all and use a 'serverless' architecture that just uses a database and a script for each API. Or was it a comment on the DB solution to use with a backend server?

- If the former, I think that could be a cool thing to aim for but I don't have much experience in serverless architecture, and it feels like quite a complicated thing to set up. Would we need to get our data factory to output data in a form that can be used with serverless scripts?
- If the latter, do we need a DB at all? I was imagining the simplest version of a backend would just be a Node server that reads the CSVs on startup and holds the initiatives in memory (like what the front-end currently does for existing maps). Since only read operations are needed, maybe this would also perform better than reading from a database?

Anyway, this is stuff to discuss in our whiteboard 😊

**Comment by rogup** [comment]
Hapi/Swagger https://github.com/krakenjs/hapi-openapi

**Comment by rogup** [comment]
@wu-lee 
**Discussion from whiteboard**
- Nick in favour of making mocks and prototype in NocodDB before making backend. Rohit in favour of not doing extra work since we have confidence from previous demos that it will be ok.

**Path forwards that we've decided**
- As a prototype, just have mock files on a server for each response (eg. list of IDs for search result) which are served to FE.
- Get going with making the BE.
  1. Use Swagger to create APIs
  2. Generate Hapi routes (since we know Hapi works reliably in LX, or choose other common framework if not possible with Hapi)

**Target**:
- set up the mock files and Swagger APIs by the end of Monday
- create simple BE server that serves mock responses by Thurs

**Comment by rogup** [comment]
@wu-lee has done some more investigation into frameworks e.g. Hapi or something else.

SwaggerHub can generate a stub app in NodeJS, but this doesn't work with Hapi. Hapi doesn't seem to have a tool for generating server-side code. There is only a tool for auto-generating openapi specs from Hapi code, which would be useful if the code becomes the "source of truth" later.

Other frameworks which seems to have better support for openapi are:
- NestJS (although this seems to be developer marmite)
- Fastify https://www.npmjs.com/package/fastify-openapi-glue
- Express https://openapi-generator.tech/docs/generators/nodejs-express-server

Fastify seems to [do very well in benchmarks](https://medium.com/deno-the-complete-reference/express-vs-fastify-vs-hapi-vs-koa-hello-world-performance-comparison-dd8cd6866bdd) compared to other frameworks, it looks like it is fairly simple to use, and development looks like it will be fast if we use fastify-openapi-glue.

So let's go with this. I'll make a ticket for this work.
