### ISSUE TITLE
[CWM] Investigate API validation libraries for MykoMap

### ISSUE THREAD

**Issue by ms0ur1s** [DigitalCommons/mykomap#269]
Created after whiteboard #267 

### Description:
Research and evaluate API validation libraries that can be integrated into the MykoMap backend. The chosen library should ensure that incoming requests are properly validated against the API schema, as defined in the Swagger spec.

### Objectives:
- Identify potential validation libraries compatible with the tech stack.
- Compare the pros and cons of each library, considering factors like ease of integration, performance, and community support.
- Recommend the best library for use in MykoMap.

### Acceptance Criteria:

-  A short report or summary document comparing the chosen validation libraries.
-  A recommendation for which library to use, supported by reasoning.
-  Create a follow-up issue to integrate the chosen library into the MykoMap backend.

**Comment by wu-lee** [comment]
Just to note that Fastify, a framework which we're trialling for the back-end server, [uses AJV][1] for this.

Others I've heard of, off the top of my head, are
- [zod][2]
- [yup][3]

There are quite a lot of others I think. I did have an article comparing these to hand once, when I was researching this for Mykomap config validation, but I can't find it again at the moment.

[1]: https://fastify.dev/docs/latest/Reference/Validation-and-Serialization/#error-handling
[2]: https://zod.dev/
[3]: https://github.com/jquense/yup

**Comment by rogup** [comment]
I was having a look at few different options and this looks promising, and works nicely with a front-end
https://trpc.io/

It can integrate easily with fastify and uses Zod, which people seem to say works well with Typescript (on that note, I think we also need to convert the BE to typescript soon, so that it doesn't become a big task to change it later).

Then, we can generate the openapi spec from our tRPC routes, as the code changes.
