### ISSUE TITLE
[CWM] Build mock data for MykoMap API responses and create unit tests

### ISSUE THREAD

**Issue by ms0ur1s** [DigitalCommons/mykomap#271]
Created after whiteboard #267

### Description
Create mock data, in the form of static files on the backend server, that can be used to simulate API responses during development and testing. Additionally, build Mocha unit tests to ensure that the API endpoints return the correct data and handle edge cases properly.

### Objectives
- Develop mock data covering all major API responses (e.g., initial data load, marker data, search results).
- Implement Mocha unit tests for all API endpoints using the mock dataset (seeing how the Mocha UTs work in the LX backend codebase may be helpful)
- Ensure tests cover both success cases and potential failure modes (e.g., invalid data, empty responses).

### Acceptance Criteria
- Mock data responses are available for use within the development environment.
- Unit tests are written for all API endpoints and pass consistently.
- Documentation on how to run and update the tests is provided.

**Comment by rogup** [comment]
I think this ticket for the backend is kind of covered by https://github.com/DigitalCommons/mykomap-monolith/issues/1 based on the whiteboard that we did specifically for the backend. I don't think it makes sense to do UTs at this stage, since we don't have any logic, we'll just be serving mock data. UTs will be useful when we come to writing the actual logic.
